### ISSUE TITLE
{"error":"bytearray index out of range"}

### ISSUE THREAD

**Issue by exqua** [rdagger/Expo-Solar-Tracker#3]
Hi there,

Can you help me out? i get this error when i do: curl -i http://127.0.0.1:5000/solar

HTTP/1.0 503 SERVICE UNAVAILABLE
Content-Type: application/json
Content-Length: 41
Server: Werkzeug/0.14.1 Python/2.7.13
Date: Sun, 06 Jan 2019 01:00:15 GMT

{"error":"bytearray index out of range"}

greetings

**Comment by rdagger** [comment]
The 503 error indicates an IndexError or IOError.  It's probably a hardware/wiring issue.  Are you sure you have a compatible MPPT controller?

**Comment by exqua** [comment]
Good morning, i have an MPPT controller from Epever 30A. Wiring i double checked. I have installed the last raspbian image (lite version) so i needed to install some libs and flask.

**Comment by rdagger** [comment]
Do you have a link to the Epever model?  Is the model of the optional LCD display MT5 or MT50?

**Comment by exqua** [comment]
Hi,
https://www.ev-power.eu/Solar-Systems/MPPT-Solar-Regulator-12-24-V-Tracer-A-30A-Input-100V-Tracer3210A.html
The model number is Tracer3210A.

Mt50 is the display

**Comment by rdagger** [comment]
The MT50 is RS485 (not TTL).  Only controllers with support for the optional MT5 display are compatible with the XXV Tracer library used in this repo.  I haven't tried it, but the following repo might work:  https://github.com/alexnathanson/EPSolar_Tracer
