### ISSUE TITLE
I upgraded to Expo 2.10.010522 on my Iphone 

### ISSUE THREAD

**Issue by branx86** [rdagger/Expo-Solar-Tracker#4]
Iphone Expo updated to 2.10.010522 now solar-tracker complains that Expo SDK v25.0.0, but this copy of Expo Client  requires at least v26.0.0 The author should update their experience to a newer Expo SDK version. Not sure how to fix the problem. Can you help once again I greatly thankyou for your program.

**Comment by rdagger** [comment]
Upgraded to Expo 32.
