### ISSUE TITLE
Hi New Expo SDK 33

### ISSUE THREAD

**Issue by branx86** [rdagger/Expo-Solar-Tracker#6]
I hate to sound like a broken record could you please update the code for Expo client SDK 35.

**Comment by rdagger** [comment]
I updated to 35 but I currently don't have access to my solar equipment so I was unable to test it.  Please let me know if it works.

**Comment by branx86** [comment]
I'll will test report back to you , Thank you for this wonderful software

**Comment by branx86** [comment]
rdagger , The update works Great. Just FYI I'm using iPhone Expo on IOS 13.1.3  expo.io client app ver. 2.13.0.107069  Supported SDKs 33, 34, 35 

Thank you again for the fine software you have provided.
